name: "release-winget"
on: release

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Publish manifest with winget-create
        run: |
          # Get correct release asset
          $assets = ${{github.event.release.assets}}
          $asset

          for($i = 0; $i -lt $assets.length; $i++){ 
              if ($assets[$i] -match '.exe$') {
                  $asset = $assets[$i]
              }
          }

          # Remove 'v' and 'vfs' from the version
          $assets.tag_name -match '\d.*'
          $version = $Matches[0] -replace ".vfs",""

          # Download and run wingetcreate
          Invoke-WebRequest https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe update Microsoft.Git -u $asset.browser_download_url -v $version --o manifests -t "${{ secrets.WINGET_TOKEN }}" -s
        shell: powershell
